### ISSUE TITLE
Error connection to database error

### ISSUE THREAD

**Issue by monkrus** [gowebexamples/goreddit#1]
OS: Ubuntu 20.04
[URL](https://github.com/monkrus/pseudo-reddit)
Getting an `error connecting to database: dial tcp 127.0.0.1:5432: connect: connection refused exit status 1` 
error after running `go run cmd/goreddit/main.go` at the end of part 6, Serving HTML with the chi router.

P.S. Please advise on the best way to communicate with you on similar issues.

**Comment by dxps** [comment]
@monkrus This is a standard error related to the fact that you (this app or any other Postgres client) could not connect to the database. Most definitely, your database listens on another interface (other than localhost or 127.0.0.1) or port (other than 5432).

Being on Ubuntu, try running `netstat -ntl` to see which ports are being open (in LISTENING mode). That should give you a clue.

**Comment by monkrus** [comment]
Thank you @devisions, I got the following results:

tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN     
tcp6       0      0 ::1:631                 :::*                    LISTEN     
tcp6       0      0 :::5432                 :::*                    LISTEN     
tcp6       0      0 :::5441                 :::*                    LISTEN     

How do I make a change? 
P.S.   I was not able to find a postgresql.conf file

**Comment by philippta** [comment]
@monkrus 
It seems like your postgres server is either not running or not available for another reason.
To start the postgres server, from your project directory run: `make postgres` (also make sure before, that you have docker installed)

If you're very certain that the postgres server is running, but you still can not connect, please provide the output for: `sudo ss  -plt` (This checks all listening TCP ports, and shows what processes have opened it)

**Comment by monkrus** [comment]
@philippta  Thank you very much! The error disappeared after I reinstalled the docker. 


State  Recv-Q Send-Q Local Address:Port         Peer Address:Port Process                                    
LISTEN 0      4096   127.0.0.53%lo:domain            0.0.0.0:*     users:(("systemd-resolve",pid=675,fd=13)) 
LISTEN 0      5          127.0.0.1:ipp               0.0.0.0:*     users:(("cupsd",pid=232540,fd=7))         
LISTEN 0      244          0.0.0.0:postgresql        0.0.0.0:*     users:(("postgres",pid=265009,fd=5))      
LISTEN 0      128                *:http-alt                *:*     users:(("php",pid=265521,fd=3))           
LISTEN 0      5              [::1]:ipp                  [::]:*     users:(("cupsd",pid=232540,fd=6))         
LISTEN 0      4096               *:3000                    *:*     users:(("main",pid=266641,fd=10))         
LISTEN 0      244             [::]:postgresql           [::]:*     users:(("postgres",pid=265009,fd=6))
