### ISSUE TITLE
Parsing templates with every request

### ISSUE THREAD

**Issue by mqrc81** [gowebexamples/goreddit#3]
Instead of `tmpl := template.Must(template.ParseFiles("templates/layout.html", "templates/user_register.html"))` with each request, which is unnecessarily slow, you should parse all of the files in the `init()` function once, and then access them via a var or map.

**Comment by gobijan** [comment]
I think your observation is not true. The functions are called only once in the NewHandler call which is happening in main.
The defined functions on handler return a function after parsing etc. that are then used afterwards all the time a url is called.
So voting to close this issue ;D

**Comment by mqrc81** [comment]
I've heard otherwise previously but I'll just take your word for it :)

> I think your observation is not true. The functions are called only once in the NewHandler call which is happening in main.
> The defined functions on handler return a function after parsing etc. that are then used afterwards all the time a url is called.
> So voting to close this issue ;D

**Comment by gobijan** [comment]
Don't just take my word for it or base your assumptions on what you hear. You can try it out by adding a fmt.Println("hello from before template parsing") above the line where you parse the template in one of your handlers. You will see that it only gets printed out once when the application is initialized. That should prove it :)
